name: Inputs

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "an environment to apply this stuff to"
        required: true
        type: choice
        options:
        - dev
        - demo
        - developer

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
     environment: ${{ steps.check_inputs.outputs.environment }}
    steps:
      - name: enrich inputs
        id: check_inputs
        run: echo "environment=$(echo ${{inputs.environment}}-is-an-env)" >> $GITHUB_OUTPUT
  
  check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: validate inputs
        run: echo ${{ needs.build.outputs.environment }}
