# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: generate a dummy RSA key
        run: |
          openssl genrsa -out ugly.pem
          value=$(cat ugly.pem|base64|tr -d '\n')
          echo "::add-mask::${value}"


      # Runs a set of commands using the runners shell
      - name: Verify
        run: |
          echo "Let'see"
          cat ugly.pem|base64 | tr -d '\n'
  
  deploy:
    # faked job
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 10s
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s
          
      - name: Do something
        run: |
          echo "Hello something?"

  send:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: int128/datadog-actions-metrics@v1
        with:
          # create an API key in https://docs.datadoghq.com/account_management/api-app-keys/
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
          collect-job-metrics: true
